data = (10, 20, 30, 20, 10)

print(data.count(20))
print(data.index(30))
print(len(data))
print(max(data))
print(min(data))
print(sum(data))
print(sorted(data))
print(data.__contains__(10))
print(data.__getitem__(2))
print(data.__len__())
print(data.__add__((40, 50)))
print(data.__mul__(2))
print(tuple("hello"))
print(type(data))
print(all(data))
print(any(data))
